### ISSUE TITLE
Is there a i18n support?

### ISSUE THREAD

**Issue by masterT** [imbrn/v8n#107]

**Comment by sebastianbarfurth** [comment]
What exactly would you like to see internationalized?

**Comment by masterT** [comment]
Error message, but I saw there is no message in the thrown `ValidationError`, just rule, value, cause, and target. So I'm not sure how it would apply.

**Comment by masterT** [comment]
Wouldn't be nice to have a human-readable error message with internationalizing support?

**Comment by sebastianbarfurth** [comment]
Yes, I agree. However, I believe this is not the libraries responsibility. It does provide a key, namely the rule's name, which can be used by your application to provide and localize error messages. Complete i18n support would dramatically increase this library's footprint, since it would require an additional package and at least one long string for every single rule.

Many people might use v8n internally and don't need readable error messages. All in all I just feel like this is heavy and application specific and not really something for the core of this library.
