### ISSUE TITLE
Alternating true/false validation on a value

### ISSUE THREAD

**Issue by rafaelytakei** [imbrn/v8n#170]
Hi, I'm currently having trouble with a simple validation. Basically I have an input field #name, which i'm trying to validate comparing to the nameRegex value, which should return true if it has more than 3 characters basically, everytime I press the #validate button.

However, whenever I try to validate a valid name, it alternates between true/false if I validate it more than once, when it was supposed to always return true. Do you know what could be the problem?

Here is part of my code:

`const nameRegex = /^([A-zÀ-ú '´]{3,})$/g;`

`$('#validate').on('click', function() {
        let name= $('#name').val();
        console.log(name);
        let nameValidation = tsfv.string().pattern(nameRegex).test(nome);
        console.log(nameValidation);
    })`

**Comment by imbrn** [comment]
Hello @rafaelytakei, thank you for reporting that.

Actually, the real problem seems to be related to the Regex itself. Take a look at this Stackoverflow answer about using flag "g" in a Regex (https://stackoverflow.com/a/32421712/12060534).

What I'd recommend you to do in this case it to remove the `'g'` flag from your regex, as your validating an input value only, and it makes no sense to search for more than one case.

I hope this can help you. And let me know about that :)

**Comment by rafaelytakei** [comment]
oh, it fixed the issue, the 'g' was actually useless after all, thanks for the help!
