### ISSUE TITLE
Reporting everything that's wrong with my value

### ISSUE THREAD

**Issue by VPenkov** [imbrn/v8n#24]
Disclaimer: I haven't used the library but find it very interesting. I'd like to know everything that is wrong with my value instead of taking the fail-fast approach. I would expect to receive an array of  Is there a way of doing that?

For example:
```javascript
v8n()
  .number()
  .between(0, 100)
  .even()
  .test(133);
```

could result in something like
```javascript
{
  errors: [ 'even', 'range' ]
}
```
In that case, I could tell my user that their number must be even and exceeds the predefined range.

**Comment by askmike** [comment]
Cleanest way would be to introduce a new function next to `check` and `test`. Maybe something like `filter`? Since all chained rules are stored in [an array](https://github.com/imbrn/v8n/blob/master/src/v8n.js#L54) this shouldn't be very hard to implement (eg. first filter non passing then map to rule name).

**Comment by VPenkov** [comment]
`testAll` also sounds reasonable.
 The hard part about this one are the types. Can't figure out what to suggest if we expect something to be a number and it's a string. That would pretty much mean that we can't perform the number validations in a clean way so types probably should still follow the fail-fast approach and only build up the array from the rest of the errors.

**Comment by imbrn** [comment]
This seems like a very interesting feature.

The benefit of using the first-fail approach for the `test` and `check` functions is that we do not depend on a strict verification by the engine about the rules, so it's a developer responsibility to construct a reasonable strategy for his/her use case. We should keep this flexibility in mind.

For the returned value, I think we should work with `Rule` objects, as it's already part of the public API. And this is going to provide a better abstraction and flexibility for more use cases. Also, that's not hard to get an array as initially suggested by @VPenkov, we just need to use a simple `map` and get the name of each rule.

About the validation process, I think we should keep the actual approach of testing a value and considering this an invalid value if something goes wrong, like an exception.

So we could consider an example:

```javascript
const result = v8n()
  .number()
  .between(5, 10)
  .not.even()
  .testAll("A string value"); // could be named filter, checkAll
```

That would return an array of rule objects containing `number` and `between` as failed rules:

```javascript
// result:
[
  { name: `number`, fn: λ, args: [], false },
  { name: `between`, fn: λ, args: [5, 10], false }
]
```

Note that the `even` rule is not considered a failed one because of the `not` modifier before it. `"A string value"` is actually `not` an even value. So the `not` modifier behavior should be treated as the opposite of a normal rule.

What do you guys think about that? And thank you for your feedback.

**Comment by VPenkov** [comment]
Looks great. The tricky part would be
```javascript
const result = v8n()
  .number()
  .between(5, 10)
  .not.even()
  .testAll("11");
```

Note that `"11"` is a string. When I submitted this issue, I didn't know what solution to offer there. Now I've thought of something but this is a hasty/hacky solution, I'm sure people smarter than me can suggest something more clever. Here we go.
```javascript
const result = v8n()
  .as(Number)
  .between(5, 10)
  .not.even()
  .testAll("11");
```
...the `as` method might try to cast the value to the desired type, then fail if it's not valid. For instance, in the current case, it may try to do `Number(<our value>)`, then check if `isNaN(<the cast value>)`. If it's not valid, then skip the rest of the checks because they are impossible. This would be useful when checking the values of number inputs that end up being strings and/or when the server does type casting.

And the final step would be to pass an `allowFastFail` option somewhere. That could allow us to have the same code both on server and client side with the difference being that option.

**Comment by sebastianbarfurth** [comment]
I've started this. I finished the functionality for the current working set of rules.

You can clone [my repo](https://github.com/sebastianbarfurth/v8n/tree/improvement/all-errors) and check out ``improvement/all-errors`` to take a look. A test is implemented.

Since the ``.as()`` functionality @VPenkov mentioned is not a thing yet, this will probably do. You guys should take a look and then I could pull-request.

**Comment by sebastianbarfurth** [comment]
There hasn't been any feedback here, is this not wanted anymore?

I also believe that ``as()`` is not really necessary, since you can just pass ``Number("11")`` to ``test()`` and get expected results.
